steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 6.x SDK'
    inputs:
      packageType: sdk
      version: 6.x

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Restore'
    inputs:
      command: 'restore'
      arguments: '--verbosity minimal'

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration) --no-restore'

#  - task: DotNetCoreCLI@2
#    displayName: 'Dotnet Publish'
#    inputs:
#      command: 'publish'
#      publishWebProjects: false
#      projects: '$(backendProjectPath)'
#      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/$(BuildConfiguration) --no-build'
#
#  - task: PublishBuildArtifacts@1
#    displayName: 'Publish Artifacts'
#    inputs:
#      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#      ArtifactName: 'drop'
#      publishLocation: 'Container'